version: "3"
services:
  texlive: 
    build:
      args:
        - BASE_IMAGE=paperist/texlive-ja:latest
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workdir
      - ~/.ssh:/root/.ssh
    entrypoint: bash
    tty: true
    working_dir: /workdir
    command: exec /bin/bash